server:
  port: 8055

spring:
  application:
    name: job

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123kkk
    url: jdbc:mysql://localhost:3306/job?serverTimeout=Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 文件上传限制
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1m

  #邮件服务配置
  mail:
    host: smtp.qq.com
    username: beibei-job@foxmail.com
    password: cljinfcdlcgzbeaa
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.milk.job.model.pojo


qiniu:
  accessKey: fZdZcEkWr4eVDUo3CuMTjtVxAEQx2eBU0tbq6Iaj
  secretKey: dyM0vsKz0BqkrRZsAdsZVvuVqNqTvqgFAYXW7XML
  bucket: beibei-aunt
  baseUrl: http://images.beibeiaunt.icu/

